name: mvvm_practise
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^9.0.0
  dartz: any
  dio: any
  flutter:
    sdk: flutter
  flutter_bloc: any
  font_awesome_flutter: any
  get: any
  go_router: any
  google_fonts: any
  equatable: any

dev_dependencies:
  equatable: any
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: GT
      fonts:
        - asset: assets/fonts/GT-Sectra-Fine-Regular.ttf
