name: mvvm_practise
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc : any
  get : any
  font_awesome_flutter: any
  google_fonts : any
  go_router : any
  dartz : any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  equatable : any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family : GT
      fonts:
        - asset : assets/fonts/GT-Sectra-Fine-Regular.ttf